version: '3'

services:
  app:
    build: .
    environment:
      - TERM=xterm
    ports:
      - "8000"
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - /etc/letsencrypt/live/lostnfound.tech:/ssl
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
